from ast import literal_eval

import pandas as pd
from inflection import pluralize, singularize

from ..initialization.chemical._load_mesh import load_mesh


def remove_plural(synonyms):
    # A simple heuristic: Since the synonyms are generated by appending all plural
    # forms at the end, we can find the plural form for the first term and return
    # the terms before it. If the first term is available for pluralization, e.g.,
    # parantheses, we use the second term.
    if len(synonyms) == 1:
        return {"foodon": synonyms}

    for i, s in enumerate(synonyms):
        sp = pluralize(s)
        try:
            i_end = synonyms[i + 1 :].index(sp) + i + 1
            return {"foodon": synonyms[:i_end]}
        except ValueError:
            pass

        ss = singularize(s)
        try:
            i_end = synonyms[i + 1 :].index(ss) + i + 1
            return {"foodon": synonyms[:i_end]}
        except ValueError:
            continue

    return {"foodon": synonyms}


def add_synonyms_display(row, mesh):
    if row["entity_type"] == "food":
        # If FoodOn, remove plurals.
        if "foodon" in row["external_ids"]:
            row["_synonyms_display"] = remove_plural(row["synonyms"])
    elif row["entity_type"] == "chemical":
        if "chebi" in row["external_ids"]:
            row["_synonyms_display"]["chebi"] = row["synonyms"]
        if "mesh" in row["external_ids"]:
            mesh_id = row["external_ids"]["mesh"][0]
            if mesh_id in mesh.index:
                row["_synonyms_display"]["mesh"] = mesh.loc[mesh_id]
        # if 'chebi' not in row['external_ids'] and 'mesh' not in row['external_ids']:
        #     if 'cdno' in row['external_ids']:
        #         row['_synonyms_display']['cdno'] = row['synonyms']
        #     else:
        #         row['_synonyms_display']['fdc_nutrient'] = row['synonyms']
    return row


if __name__ == "__main__":
    entities = pd.read_csv(
        "outputs/kg/entities.tsv",
        sep="\t",
        converters={
            "synonyms": literal_eval,
            "external_ids": literal_eval,
        },
    )
    entities["_synonyms_display"] = [{} for _ in range(len(entities))]

    mesh = load_mesh()
    entities = entities.progress_apply(
        lambda row: add_synonyms_display(row, mesh),
        axis=1,
    )
    entities["_synonyms_display"].to_csv(
        "synonyms_display.tsv",
        sep="\t",
        index=False,
    )
